# Generated by Django 4.0.5 on 2022-07-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.TextField(max_length=4000),
        ),
    ]
