# Generated by Django 4.0.5 on 2022-07-17 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0002_alter_entrada_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.date(2022, 7, 17)),
        ),
    ]
