# Generated by Django 4.0.5 on 2022-07-17 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0003_entrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 7, 17)),
        ),
    ]
