# Generated by Django 4.0.5 on 2022-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0004_alter_entrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(),
        ),
    ]
