# Generated by Django 4.0.5 on 2022-07-18 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posteos', '0005_alter_entrada_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-creado']},
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='fecha',
        ),
        migrations.AddField(
            model_name='entrada',
            name='creado',
            field=models.DateField(default=datetime.date(2022, 7, 17)),
        ),
    ]
